

"""""""" BASIC OPTIONS

" Set off compatibility with vi editor
" TODO: what does it mean?
set nocompatible

" Enable syntax and plugins (for netrw)
syntax enable
filetype plugin on

" turn hybrid line numbers on
set number relativenumber
set nu rnu

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" Set smart tab behaviour with default tab size = 2
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set autoindent

" Read .vimrc file from current directory
set exrc



" Show vertical stop
" set cc=100

"""""""" FINDING FILES

" Search down into subfolders
" Provides tab-completion for all file-related tasks
" define specific set path in project
set path+=**

" Display all matching files when we tab complete
set wildmenu

" With this options we can:
" - hit tab to :find by partial match
" - use * to make it fuzzy
" - :b lets you autocomplete any open buffer




"""""""" TAG JUMPING

" Create the `tags` file (requires ctags to be installed)
command! MakeTags !ctags -R --extras=+f .

" After creation tags in project we can:
" - use ^] to jump to tab under cursor
" - use g^] for ambiguous tags
" - use ^t to jump back up the tag stack

" Consider also rusty-tags.vi file as a tags source for rust projects
" autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/


"""""""" AUTOCOMPLETE

" HIGHLIGHTS:
" - ^x^n for JUST this file
" - ^x^f for filenames (works with our path trick!)
" - ^x^] for tags only
" - ^n for anything specified by the 'complete' option
" - use ^n and ^p to go back and forth in the suggestion list
" - read other good stuff in |ins-completion|



""""""""" FILE BROWSING

" Tweaks for browsing
" disable banner
let g:netrw_banner=0
" open in prior window
let g:netrw_browse_split=4
" open splits to the right
let g:netwr_altv=1
" tree view
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" With this options we can:
" - :edit a folder to open a file brower
" - <CR>/v/t to open in an h-split/v-split/tab
" - check |netw-browse-maps| for more mappings


" rust.vim plugin sets the recommended style for rust files
" with tabstop=8 shiftwidth=4 etc.
" for a while I want to leave HMP like style
" so setting variable below to 0 force rust.vim not to set the style
" let g:rust_recommended_style = 0

" autocomplete brackets
" inoremap ( ()<left>
" inoremap [ []<left>
" inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

" autosave
" just press \s in normal mode
noremap <Leader><space> :update<CR>


" highlight current line
set cursorline


" make backspace work in any state
set backspace=indent,eol,start




"""""""""""""" SEARCH

" To search specific item you can:
" - copy it using 'yank' command
" - paste it into command line mode using ctrl_r + \" key

" Highligh matched string
set hlsearch

" Enable incremental search
set incsearch

" Press Space to turn off highlighting and clear any message already displayed.
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

packloadall

" from: https://github.com/dense-analysis/ale#standard-installation
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" Setup persistent updo
set undofile
set undodir=~/.vim/undodir

let mapleader = '\'


let g:auto_save = 1  " enable AutoSave on Vim startup




"""""" vim.test config
nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>

let test#strategy = "vimterminal"



" Edit vimr configuration file
nnoremap <Leader>ve :tabnew $MYVIMRC<CR>
" " Reload vimr configuration file
nnoremap <Leader>vr :source $MYVIMRC<CR>


" FZF shortcuts
nnoremap <silent> <leader>f :FZF<cr>
nnoremap <silent> <leader>F :FZF ~<cr>

nnoremap <silent> <leader>t :Tags<cr>
nnoremap <silent> <leader>T :Tags <word><cr>

nnoremap <silent> <leader>w :Rg<cr>
nnoremap <silent> <leader>W :Rg <C-r><C-w><cr>

" completion
nnoremap <leader>gl :YcmCompleter GoToDeclaration<CR>




let g:airline_theme='afterglow'
let g:afterglow_inherit_background=1
let g:afterglow_use_italics=0
colorscheme afterglow
"colorscheme shine


set nospell
autocmd ColorScheme *
    \ highlight SpelunkerSpellBad cterm=underline ctermfg=247 gui=underline guifg=#9e9e9e |
    \ highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=NONE gui=underline guifg=NONE


" set tabsize = 4 for javascript and typescript
" taken from:
" https://stackoverflow.com/questions/158968/changing-vim-indentation-behavior-by-file-type
autocmd FileType javascript setlocal shiftwidth=4 softtabstop=4 expandtab
autocmd FileType typescript setlocal shiftwidth=4 softtabstop=4 expandtab
autocmd FileType yaml setlocal shiftwidth=4 softtabstop=4 expandtab

" setup for https://github.com/pseewald/vim-anyfold
filetype plugin indent on " required
syntax on                 " required

autocmd Filetype * AnyFoldActivate               " activate for all filetypes

set foldlevel=99 " Open all folds

" Start NERDTree when Vim starts with a directory argument.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') | execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif


" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

" Mirror the NERDTree before showing it. This makes it the same on all tabs.
nnoremap <C-n> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
nmap <F6> :NERDTreeToggle<CR>



set rtp+=/usr/local/opt/fzf

let g:ycm_show_diagnostics_ui = 1
let g:ycm_enable_diagnostic_signs = 0
let g:ycm_enable_diagnostic_highlighting = 0

autocmd FileType python set equalprg=autopep8\ -

let g:copilot_filetypes = {
      \  '*': v:true
      \}

imap <silent><script><expr> <C-Y> copilot#Accept("\<CR>")
imap <silent><script><expr> <C-C> copilot#Suggest()
imap <silent><script><expr> <C-L> copilot#Next()
imap <silent><script><expr> <C-H> copilot#Previous()
let g:copilot_no_tab_map = v:true

" Function to source only if file exists {
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
  endif
endfunction
" }

call SourceIfExists("~/.work.vimrc")
