# .xsession

xrdb -merge .Xresources

# set up wallpaper image
feh --bg-scale ${HOME}/background.jpg &

# set up transparency
xcompmgr &

# start up screensaver service
xscreensaver-command -exit
xscreensaver -no-splash &

# start up automount usb storages
udiskie &

# run xmonad
i3
