zstyle :omz:plugins:ssh-agent identities thedilletante_ed25519 work_ringcentral_gitlab_ed25519

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

ZSH_DISABLE_COMPFIX=true
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(
  aliases
	git
	autopep8
	battery
	rust
	colored-man-pages
	fzf
  ssh-agent
  brew
  archlinux
  #zsh-autosuggestions
  #zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

alias ls=lsd
alias grep=rg
alias python=python3
if [[ `uname` != "Darwin" ]]; then
  alias open=xdg-open
fi

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

#if [ "$TMUX" = "" ]; then tmux attach || tmux; fi

export SFU_REPO=~/proj/sfc

alias p=pushd
alias o=popd

alias week_number='python -c "import datetime; print(datetime.datetime.now().isocalendar()[1])"'
alias cat=bat

export RPROMPT="%t"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.env_secrets ] && source ~/.env_secrets
[ -f ~/.cargo/env ] && source ~/.cargo/env
[ -f ~/proj/work_notes/config/zshrc ] && source ~/proj/work_notes/config/zshrc
export NVM_DIR="$HOME/.nvm"
if type brew &>/dev/null; then
  [ -s "$(brew --prefix asdf)/libexec/asdf.sh" ] && source "$(brew --prefix asdf)/libexec/asdf.sh"
  [ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && . "$(brew --prefix nvm)/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
fi

export PATH=$PATH:${HOME}/proj/tools/beauty_log:$HOME/proj/work_notes/scripts
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH=$PATH:~/.local/bin
[ -d ~/.cargo/bin ] && export PATH=$PATH:~/.cargo/bin
[ -d ~/go/bin ] && export PATH=$PATH:~/go/bin
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/thedilletante/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
[ -f "$HOME/.asdf/asdf.sh" ] && source "$HOME/.asdf/asdf.sh"
export PATH="/opt/homebrew/opt/ccache/libexec:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/lib/ccache/bin:$PATH"

if [[ `uname` != "Darwin" ]]; then
  if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    #exec startx
	fi
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
  alias fd=fdfind
  export PATH="/usr/lib/ccache:$PATH"
else
  alias go_x86_64="arch -x86_64 /bin/zsh"
  export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
  export PATH="${PATH}:$(brew --prefix llvm)/bin"
  ulimit -n 10240
  export PATH="/opt/homebrew/opt/ccache/libexec:$PATH"
fi

export FZF_DEFAULT_COMMAND='rg --files'

HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
SAVEHIST=999999999
HISTSIZE=${SAVEHIST}

if type brew &>/dev/null; then
  source <(kubectl completion zsh)
fi

if type gh &>/dev/null; then
  eval "$(gh copilot alias -- zsh)"
fi

export PATH=$PATH:/nix/var/nix/profiles/default/bin/

alias fzf_branch='gb | fzf | xargs | sed "s/\* *//"'
alias fzf_branch_multi='gb | fzf -m | xargs | sed "s/\* *//"'
alias fzf_branch_all='gba | fzf | xargs | sed "s/\* *//" | sed "s|remotes/||"'
alias fzf_branch_all_multi='gba | fzf  -m| xargs | sed "s/\* *//" | sed "s|remotes/||"'

export EMOJI_CLI_USE_EMOJI=1
EMOJI_CLI_PATH=~/.zsh_plugins/emoji-cli/emoji-cli.zsh
if [ -f "${EMOJI_CLI_PATH}" ]; then
  source "${EMOJI_CLI_PATH}"
fi
