zstyle :omz:plugins:ssh-agent identities thedilletante_ed25519 work_ringcentral_gitlab_ed25519

ZSH_DISABLE_COMPFIX=true
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(
	git
	autopep8
	battery
	rust
	colored-man-pages
	fzf
  tmux
  ssh-agent
  brew
  archlinux
)

source $ZSH/oh-my-zsh.sh

alias ls=exa
alias grep=rg
alias python=python3

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

if [ "$TMUX" = "" ]; then tmux attach || tmux; fi

export SFU_REPO=~/proj/sfc

alias p=pushd
alias o=popd

alias week_number='python -c "import datetime; print(datetime.datetime.now().isocalendar()[1])"'

export RPROMPT="%t"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.env_secrets ] && source ~/.env_secrets
[ -f ~/.cargo/env ] && source ~/.cargo/env
[ -f ~/proj/work_notes/config/zshrc ] && source ~/proj/work_notes/config/zshrc
export NVM_DIR="$HOME/.nvm"
if type brew &>/dev/null; then
  [ -s "$(brew --prefix nvm)/nvm.sh" ] && source "$(brew --prefix nvm)/nvm.sh"  # This loads nvm
  [ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && . "$(brew --prefix nvm)/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
fi

source <(kubectl completion zsh)

export PATH=$PATH:${HOME}/proj/tools/beauty_log:$HOME/proj/work_notes/scripts
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH=$PATH:~/.local/bin
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/thedilletante/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
[ -f "$HOME/.asdf/asdf.sh" ] && source "$HOME/.asdf/asdf.sh"
export PATH="/opt/homebrew/opt/ccache/libexec:$PATH"
export PATH="/usr/lib/ccache/bin:$PATH"

if [[ `uname` != "Darwin" ]]; then
  if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  	exec startx
	fi
fi
